import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { headers } from 'next/headers'

import Provider from "./provider";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/utils/config";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Markium",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get('cookie')
  )
  return (
    <html lang="en" >
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-poppins bg-black`}
      >

      <Provider initialState={initialState}>
          {children}
      </Provider>
      </body>
    </html>
  );
}